team_abbreviations = {
    "Manchester City": "MCI",
    "Arsenal": "ARS",
    "Manchester United": "MUN",
    "Newcastle United": "NEW",
    "Liverpool": "LIV",
    "Brighton & Hove Albion": "BHA",
    "Aston Villa": "AVL",
    "Tottenham Hotspur": "TOT",
    "Brentford": "BRE",
    "Fulham": "FUL",
    "Crystal Palace": "CP",
    "Chelsea": "CHE",
    "Wolverhampton Wanderers": "WOL",
    "West Ham United": "WHU",
    "AFC Bournemouth": "BOU",
    "Nottingham Forest": "NFO",
    "Everton": "EVE",
    "Leicester City": "LEI",
    "Leeds United": "LEE",
    "Southampton": "SOU",
    'Sheffield United': "SHU",
    "Burnley": "BUR",
    "Luton Town": "LUT",
    "Norwich City": "NOR",
    "West Bromwich Albion": "WBA",
    "Cardiff City": "CAR",
    "Huddersfield Town": "HUD",
    "Watford": "WAT"
}
